services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: minio
    ports:
      - "${MINIO_PORT_API_EXTERNAL}:${MINIO_PORT_API_INTERNAL}"
      - "${MINIO_PORT_UI_EXTERNAL}:${MINIO_PORT_UI_INTERNAL}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
      - ./minio/init/init-bucket.sh:/init-bucket.sh
    command: server --console-address ":${MINIO_PORT_UI_INTERNAL}" /data
    restart: unless-stopped

  minio-init:
    image: minio/mc
    container_name: minioinit
    depends_on:
      - minio
    volumes:
      - ./minio/minio_data:/data
    entrypoint: >
      sh -c "
        sleep 5 &&
        mc alias set local http://${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb local/${MINIO_BUCKET} || true &&
        mc cp --recursive /data local/${MINIO_BUCKET}
      "
    restart: "no"

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/postgres_data:/postgresql/data
    restart: unless-stopped

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    container_name: weaviate
    command: ["--host", "0.0.0.0", "--port", "8080", "--scheme", "http"]
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
  
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-mpnet-base-v2
    container_name: transformers
    environment:
      ENABLE_CUDA: '0'
    ports:
      - "8081:8080"
  verba:
    image: semitechnologies/verba:latest
    container_name: verba
    ports:
      - "8082:8000"
    environment:
      - VERBA_WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate

  portainer:
    image: ${PORTAINER_IMAGE}
    container_name: portainer
    ports:
      - "${PORTAINER_PORT_EXTERNAL}:${PORTAINER_PORT_INTERNAL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
  portainer_data:
  weaviate_data: